### ISSUE TITLE
Add owner of poolboy in hex.pm

### ISSUE THREAD

**Issue by getong** [devinus/poolboy#109]
Just like proper-testing/proper#176, a new owner of the proper is added in hex.pm.
I think @devinus  you should add @Vagabond  to be a new owner of the poolboy in the hex.pm, and finally push poolboy 1.5.2 to the hex.pm.

**Comment by getong** [comment]
@Vagabond 
I find out a link, it might be help.
https://hex.pm/policies/dispute#if-you-wish-to-acquire-an-existing-package-name
Would you do the instruction as the page described?

**Comment by Vagabond** [comment]
I have started this process, we will see where it goes.

**Comment by getong** [comment]
@Vagabond 
I find out that you are the owner of poolboy in the hex.pm, would you publish the new tag to hex.pm?

**Comment by Vagabond** [comment]
Done!
