### ISSUE TITLE
Pool stops working after poolboy:transaction times out.

### ISSUE THREAD

**Issue by eshubin** [devinus/poolboy#64]
I created a sample project, which reproduces and error in poolboy https://github.com/eshubin/poolboy_test.

What happens is that poolboy:transaction function terminates via timeout
https://github.com/eshubin/poolboy_test/blob/ver1/src/poolboy_test.erl#L35,
https://github.com/eshubin/poolboy_test/blob/ver1/src/poolboy_test.erl#L63
and then poolboy:status always returns {full,0,0,1} https://github.com/eshubin/poolboy_test/blob/ver1/src/poolboy_test.erl#L64
and all further calls of poolboy:transaction also time out https://github.com/eshubin/poolboy_test/blob/ver1/src/poolboy_test.erl#L65.
Actually code in fun is not executed at all.
All tests could be launched with "rebar eunit" in top level directory.

Is it possible to restore pool's functionality after such timeout?

**Comment by devinus** [comment]
I believe this happens because of a your super low timeout. Let me investigate.

**Comment by eshubin** [comment]
What happens there is that poolboy gen_server receives a call from the client, allocates a worker, adding it to monitors, and then client handles exit from gen_server:call which does not send 'DOWN' back to poolboy so. As a result worker is lost. That could happen not only because of small timeout, but also because of slow worker start/restart, which might happen in handle_call.
