### ISSUE TITLE
Wishlist: point at 'modern' Postgres driver

### ISSUE THREAD

**Issue by davidw** [devinus/poolboy#67]
In your examples, you point to wg's original Postgres driver, which was great work, but no longer maintained.

https://github.com/epgsql/epgsql

and

https://github.com/semiocast/pgsql

are both up to date and maintained.  The former is a fork of wg's project.

**Comment by devinus** [comment]
@davidw PR pointing to https://github.com/epgsql/epgsql and I'll accept it.

**Comment by davidw** [comment]
Thanks!

**Comment by devinus** [comment]
Glad to see the epgsql driver maintained!
