### ISSUE TITLE
compile fails with erlang 18

### ISSUE THREAD

**Issue by SergejJurecko** [devinus/poolboy#80]
OTP release 18 does not match required regex R15|R16B02|R16B03-1|17

**Comment by ericmj** [comment]
@SergejJurecko Where do you see that regex?

**Comment by SergejJurecko** [comment]
I presume this regex gets expanded from:  {platform_define, "^R", pre17}

**Comment by ericmj** [comment]
No, that justs sets a define. What version are you using? Can you try the latest one?

**Comment by SergejJurecko** [comment]
Oh right sorry my bad. I have poolboy as a dependency and rebar compile made it look like it was poolboys fault. A different dependency had that require_otp_vsn.
