### ISSUE TITLE
What is max_overflow?

### ISSUE THREAD

**Issue by laheadle** [devinus/poolboy#82]
The documentation states:

max_overflow: maximum number of workers created if pool is empty

What does this mean? When might this happen? How is this different from max_size?

**Comment by devinus** [comment]
Overflow are workers that are created and discarded on checkin when the pool is full.

**Comment by amokan** [comment]
@devinus I know you closed the issue here, but I'm wondering the same thing. If I specify a pool has a size of, say, 10 - why would I want it to overflow to more than this?

I'm just trying to understand a use-case or scenario where this makes sense. Thanks.

**Comment by devinus** [comment]
@amokan If you want to keep 10 connections around but want to allow the pool to overflow to e.g. allow 20 open connections but no more. The pool will reduce size to 10 when the 10 overflow get checked in.

**Comment by amokan** [comment]
@devinus :+1:

**Comment by devinus** [comment]
I think `overflow` makes sense in this regard. Also I copied the naming from SQLAlchemy.
