### ISSUE TITLE
How to get the list of workers

### ISSUE THREAD

**Issue by ates** [devinus/poolboy#91]
Hey,

How to get the list of workers for the specific pool ? The possible solution I found is:

```erlang
5> element(3, sys:get_state(whereis(poolname))).
[<0.430.0>,<0.429.0>,<0.428.0>,<0.427.0>,<0.426.0>]
```

It would be good to have a function like poolboy:workers/1 for that.

**Comment by ates** [comment]
Found one more:

```erlang
10> gen_server:call(poolname, get_avail_workers).
[<0.430.0>,<0.429.0>,<0.428.0>,<0.427.0>,<0.426.0>]
```

Anyway the helper function like workers/1 would be useful

**Comment by ates** [comment]
I can prepare a pull request if no objections

**Comment by ates** [comment]
ping

**Comment by devinus** [comment]
@ates Thank you for trying to improve Poolboy, however I think `workers/1` is too generic. Is it all workers? Available workers? Checked out workers? `gen_server:call(poolname, get_avail_workers)` is a public enough API.
